//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newvics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootyClub
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
        public string Mascot { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Membership_count { get; set; }
        public Nullable<int> Revenue { get; set; }
    }
}
