//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newvics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> Type { get; set; }
        public string Adress { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Photo_reference { get; set; }
        public Nullable<int> Total_rating_people { get; set; }
        public string Other { get; set; }
    
        public virtual Sports Sports { get; set; }
    }
}
